<?php
/**
 * @var $books \Book\Model\Entity\Book[]
 */
?>


<div class="well">

    <h1>Books</h1>

    <a href="<?= $this->url('book', array('action' => 'add')); ?>" class="btn btn-default">
        Create
    </a>

    <br>
    <br>

    <table class="table table-bordered books-table">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>ISBN</th>
            <th>Author</th>
            <th></th>
        </tr>
        <?php foreach($books as $book):?>
            <tr>
                <td><?=$book->getId() ?></td>
                <td><?=$book->getTitle() ?></td>
                <td><?=$book->getIsbn() ?></td>
                <td><?=$book->getAuthor() ?></td>
                <td>
                    <!--<a href="<?/*= $this->view->url(['controller' => 'books', 'action' => 'detail']) */?>">-->
                    <a href="<?= $this->url('book', array('action' => 'detail', 'id' => $book->getId())); ?>">
                        <span class="glyphicon glyphicon-eye-open"></span>
                    </a>
                    <a href="<?= $this->url('book', array('action' => 'update', 'id' => $book->getId())); ?>">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                    <a href="<?= $this->url('book', array('action' => 'remove', 'id' => $book->getId())); ?>">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

    <?php /*foreach($books as $book):*/?><!--
        <div class="book">
            <textarea id="book-<?php /*echo $book->getId() */?>"><?php /*echo $book->getTitle() */?></textarea>
            <a href="#" id="remove-<?php /*echo $book->getId(); */?>"class="delete-book">X</a>
        </div>
    <?php /*endforeach; */?>
    <div id="create">+</div>-->

</div>
<div class="clear-both"></div>