<?php

$title = 'Edit Book #' . $this->id;
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'book',
    array(
        'action' => 'update',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id')) . '<br>';
echo $this->formRow($form->get('title')) . '<br>';
echo $this->formRow($form->get('isbn')) . '<br>';
echo $this->formRow($form->get('author')) . '<br>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();